// This file will be auto-generated by Supabase CLI
// Run: npm run db:types
// For now, using placeholder types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      daily_checkins: {
        Row: {
          id: string
          user_id: string
          check_date: string
          energy_score: number | null
          mood_score: number | null
          libido_score: number | null
          sr_day_count: number | null
          morning_notes: string | null
          evening_notes: string | null
          morning_completed_at: string | null
          evening_completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          check_date: string
          energy_score?: number | null
          mood_score?: number | null
          libido_score?: number | null
          sr_day_count?: number | null
          morning_notes?: string | null
          evening_notes?: string | null
          morning_completed_at?: string | null
          evening_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          check_date?: string
          energy_score?: number | null
          mood_score?: number | null
          libido_score?: number | null
          sr_day_count?: number | null
          morning_notes?: string | null
          evening_notes?: string | null
          morning_completed_at?: string | null
          evening_completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Other tables will be generated by Supabase CLI
    }
  }
}
